export const PortfolioData = [
    {
      id: "1801",
      name: "My best client",      
      url: "https://image.shutterstock.com/z/stock-photo-the-word-link-and-serious-businessman-with-hands-on-hips-against-futuristic-black-and-blue-180015809.jpg",
      category: ["all", "React"],
    },
    {
      id: "1802",
      name: "It is a really cool website",
      url: "https://image.shutterstock.com/z/stock-photo-businessman-with-hands-on-hips-against-doors-opening-revealing-light-174824924.jpg",
      category: ["all", "Angular"],
    },
    {
      id: "1803",
      name: "It is a really cool website",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRM9BkXSFavVhEdw0Frkkku5hF3-F_zuKv2yQ&usqp=CAU",
      category: ["all", "Ecommerce"],
    },
    {
      id: "1804",
      name: "It is a really cool website",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQlvQO1b1h_bXFSblyO5AnoULvA3ZLcDNGPCA&usqp=CAU",
      category: ["all", "Mobile"],
    },
    {
      id: "1805",
      name: "It is a really cool website",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSmUGXjA0W9BCLnj6QVx_K7UVP3CWAgMM85Dg&usqp=CAU",
      category: ["all", "3D WebGL"],
    },
    {
      id: "1806",
      name: "It is a really cool website",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSL1GvJcwTnsw5GWq9T9E9BPbrtuPiKRQTzSg&usqp=CAU",
      category: ["all", "WordPress/CMS"],
    },
    {
      id: "1807",
      name: "My best client",      
      url: "https://colorlib.com/wp/wp-content/uploads/sites/2/featured_react-templates.jpg",
      category: ["all", "React"],
    },
    {
      id: "1808",
      name: "It is a really cool website",
      url: "https://miro.medium.com/max/2530/1*Nj-vU3k0XlhfAn2yqxq49g.jpeg",
      category: ["all", "Angular"],
    },
    {
      id: "1809",
      name: "It is a really cool website",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRM9BkXSFavVhEdw0Frkkku5hF3-F_zuKv2yQ&usqp=CAU",
      category: ["all", "Ecommerce"],
    },
    {
      id: "1810",
      name: "It is a really cool website",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQlvQO1b1h_bXFSblyO5AnoULvA3ZLcDNGPCA&usqp=CAU",
      category: ["all", "Mobile"],
    },
    {
      id: "1811",
      name: "It is a really cool website",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSmUGXjA0W9BCLnj6QVx_K7UVP3CWAgMM85Dg&usqp=CAU",
      category: ["all", "3D WebGL"],
    },
    {
      id: "1812",
      name: "It is a really cool website",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSL1GvJcwTnsw5GWq9T9E9BPbrtuPiKRQTzSg&usqp=CAU",
      category: ["all", "WordPress/CMS"],
    },
    {
      id: "1813",
      name: "My best client",      
      url: "https://miro.medium.com/max/4800/1*YBQY1RMoNDsDbw8LalJTaA.png",
      category: ["all", "React"],
    },
    {
      id: "1814",
      name: "It is a really cool website",
      url: "https://ripenapps.com/blog/wp-content/uploads/2018/10/Web-Mobile-App-Development-Using-AngularJs-700x400.jpg",
      category: ["all", "Angular"],
    },
    {
      id: "1815",
      name: "It is a really cool website",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRM9BkXSFavVhEdw0Frkkku5hF3-F_zuKv2yQ&usqp=CAU",
      category: ["all", "Ecommerce"],
    },
    {
      id: "1816",
      name: "It is a really cool website",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQlvQO1b1h_bXFSblyO5AnoULvA3ZLcDNGPCA&usqp=CAU",
      category: ["all", "Mobile"],
    },
    {
      id: "1817",
      name: "It is a really cool website",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSmUGXjA0W9BCLnj6QVx_K7UVP3CWAgMM85Dg&usqp=CAU",
      category: ["all", "3D WebGL"],
    },
    {
      id: "1818",
      name: "My best client",      
      url: "https://miro.medium.com/max/4800/1*YBQY1RMoNDsDbw8LalJTaA.png",
      category: ["all", "React"],
    },
    {
      id: "1819",
      name: "My best client",      
      url: "https://miro.medium.com/max/4800/1*YBQY1RMoNDsDbw8LalJTaA.png",
      category: ["all", "React"],
    },     
  ];
